### PR TITLE
Remove getFile from service, service & route spec tests, schema and G…

### PR DESCRIPTION
**Pull request by techncl**
…raphQL fields

### CODE REVIEW

**Comment by suzannehamilton** [comment]
Is this safe to merge or is it still in use? There are some [references in tdr-consignment-export](https://github.com/nationalarchives/tdr-consignment-export/search?q=getFiles) and [tdr-generated-graphql](https://github.com/nationalarchives/tdr-generated-graphql/blob/master/src/main/graphql/GetFiles.graphql).

**Comment by techncl** [comment]
Yes

> Is this safe to merge or is it still in use? There are some [references in tdr-consignment-export](https://github.com/nationalarchives/tdr-consignment-export/search?q=getFiles) and [tdr-generated-graphql](https://github.com/nationalarchives/tdr-generated-graphql/blob/master/src/main/graphql/GetFiles.graphql).

It should be, because GraphQL query is not being called anywhere from what I can see and the Consignment Export is only using `getFiles` in the Spec tests; it's referring to a json file called get_files.json.

**Comment by suzannehamilton** [comment]
I noticed that you closed the [update in the consignment export](https://github.com/nationalarchives/tdr-consignment-export/pull/59). What's the plan for that one? It would be good to update export to use the latest generated GraphQL before we merge this, just to be sure that everything is backwards-compatible.

**Comment by techncl** [comment]
> I noticed that you closed the [update in the consignment export](https://github.com/nationalarchives/tdr-consignment-export/pull/59). What's the plan for that one? It would be good to update export to use the latest generated GraphQL before we merge this, just to be sure that everything is backwards-compatible.

Ah, yes, I should have mentioned why 🤦‍♂️ . I just did it until the frontend is merged to avoid clutter; I will reopen it once I've merged it

**Comment by techncl** [comment]
This one should be fine to merge as the consignment export is not using it

**Review by suzannehamilton — APPROVED** [review]

**Comment by suzannehamilton** [comment]
That's a lovely sight. 🙂 
Git commit summary: 1 line added, 113 removed

**Pull request merged**
